const c = @cImport({
    @cInclude("raylib.h");
    @cInclude("raymath.h");
});

pub const Vector3 = c.Vector3;
pub const Camera3D = c.Camera3D;
pub const Model = c.Model;
pub const Mesh = c.Mesh;
pub const Material = c.Material;
pub const Color = c.Color;
pub const Matrix = c.Matrix;

pub const WHITE = c.WHITE;
pub const BLACK = c.BLACK;
pub const CAMERA_PERSPECTIVE = c.CAMERA_PERSPECTIVE;
pub const KEY_W = c.KEY_W;
pub const KEY_S = c.KEY_S;
pub const KEY_A = c.KEY_A;
pub const KEY_D = c.KEY_D;
pub const KEY_Q = c.KEY_Q;
pub const KEY_E = c.KEY_E;
pub const KEY_UP = c.KEY_UP;
pub const KEY_DOWN = c.KEY_DOWN;
pub const KEY_LEFT = c.KEY_LEFT;
pub const KEY_RIGHT = c.KEY_RIGHT;
pub const KEY_SPACE = c.KEY_SPACE;
pub const KEY_LEFT_SHIFT = c.KEY_LEFT_SHIFT;

pub const InitWindow = c.InitWindow;
pub const CloseWindow = c.CloseWindow;
pub const WindowShouldClose = c.WindowShouldClose;
pub const SetTargetFPS = c.SetTargetFPS;
pub const GetFrameTime = c.GetFrameTime;
pub const GetScreenWidth = c.GetScreenWidth;
pub const GetScreenHeight = c.GetScreenHeight;
pub const IsKeyDown = c.IsKeyDown;
pub const BeginDrawing = c.BeginDrawing;
pub const EndDrawing = c.EndDrawing;
pub const BeginMode3D = c.BeginMode3D;
pub const EndMode3D = c.EndMode3D;
pub const ClearBackground = c.ClearBackground;
pub const DrawFPS = c.DrawFPS;
pub const DrawText = c.DrawText;
pub const DrawRectangle = c.DrawRectangle;
pub const DrawRectangleGradientV = c.DrawRectangleGradientV;
pub const DrawLine = c.DrawLine;
pub const DrawCircle = c.DrawCircle;
pub const DrawCircleLines = c.DrawCircleLines;
pub const LoadModel = c.LoadModel;
pub const UnloadModel = c.UnloadModel;
pub const DrawModel = c.DrawModel;
pub const DrawMeshInstanced = c.DrawMeshInstanced;
pub const TextFormat = c.TextFormat;
pub const Vector3Add = c.Vector3Add;
pub const Vector3Scale = c.Vector3Scale;
pub const Vector3Lerp = c.Vector3Lerp;
pub const MatrixScale = c.MatrixScale;
pub const MatrixRotateY = c.MatrixRotateY;
pub const MatrixTranslate = c.MatrixTranslate;
pub const MatrixMultiply = c.MatrixMultiply;
pub const MatrixIdentity = c.MatrixIdentity;
